package com.mitocode.model;
// Generated 5 abr. 2022 18:03:57 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estudiantes generated by hbm2java
 */
@Entity
@Table(name = "estudiantes", schema = "public")
public class Estudiantes implements java.io.Serializable {

	private String id;
	private int codigo;
	private int idgrupo;
	private Set<Grupo> grupos = new HashSet<Grupo>(0);

	public Estudiantes() {
	}

	public Estudiantes(String id, int codigo, int idgrupo) {
		this.id = id;
		this.codigo = codigo;
		this.idgrupo = idgrupo;
	}

	public Estudiantes(String id, int codigo, int idgrupo, Set<Grupo> grupos) {
		this.id = id;
		this.codigo = codigo;
		this.idgrupo = idgrupo;
		this.grupos = grupos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 16)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "codigo", nullable = false, precision = 8, scale = 0)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "idgrupo", nullable = false, precision = 8, scale = 0)
	public int getIdgrupo() {
		return this.idgrupo;
	}

	public void setIdgrupo(int idgrupo) {
		this.idgrupo = idgrupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estudiantes")
	public Set<Grupo> getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Set<Grupo> grupos) {
		this.grupos = grupos;
	}

}
