package com.mitocode.model;
// Generated 5 abr. 2022 18:03:57 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", schema = "public")
public class Grupo implements java.io.Serializable {

	private String id;
	private Estudiantes estudiantes;
	private Profesores profesores;
	private String asignatura;

	public Grupo() {
	}

	public Grupo(String id, Estudiantes estudiantes, Profesores profesores, String asignatura) {
		this.id = id;
		this.estudiantes = estudiantes;
		this.profesores = profesores;
		this.asignatura = asignatura;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 16)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idestudiante", nullable = false)
	public Estudiantes getEstudiantes() {
		return this.estudiantes;
	}

	public void setEstudiantes(Estudiantes estudiantes) {
		this.estudiantes = estudiantes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idprofesor", nullable = false)
	public Profesores getProfesores() {
		return this.profesores;
	}

	public void setProfesores(Profesores profesores) {
		this.profesores = profesores;
	}

	@Column(name = "asignatura", nullable = false, length = 64)
	public String getAsignatura() {
		return this.asignatura;
	}

	public void setAsignatura(String asignatura) {
		this.asignatura = asignatura;
	}

}
