package com.mitocode.model;
// Generated 5 abr. 2022 18:03:57 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "persona", schema = "public")
public class Persona implements java.io.Serializable {

	private int id;
	private String apellido;
	private Integer dni;
	private Boolean empleado;
	private String nombre;

	public Persona() {
	}

	public Persona(int id) {
		this.id = id;
	}

	public Persona(int id, String apellido, Integer dni, Boolean empleado, String nombre) {
		this.id = id;
		this.apellido = apellido;
		this.dni = dni;
		this.empleado = empleado;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "apellido")
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "dni")
	public Integer getDni() {
		return this.dni;
	}

	public void setDni(Integer dni) {
		this.dni = dni;
	}

	@Column(name = "empleado")
	public Boolean getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Boolean empleado) {
		this.empleado = empleado;
	}

	@Column(name = "nombre")
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
