package com.mitocode.model;
// Generated 5 abr. 2022 18:03:57 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profesores generated by hbm2java
 */
@Entity
@Table(name = "profesores", schema = "public")
public class Profesores implements java.io.Serializable {

	private String id;
	private int idgrupo;
	private int nivel;
	private Set<Grupo> grupos = new HashSet<Grupo>(0);

	public Profesores() {
	}

	public Profesores(String id, int idgrupo, int nivel) {
		this.id = id;
		this.idgrupo = idgrupo;
		this.nivel = nivel;
	}

	public Profesores(String id, int idgrupo, int nivel, Set<Grupo> grupos) {
		this.id = id;
		this.idgrupo = idgrupo;
		this.nivel = nivel;
		this.grupos = grupos;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 16)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "idgrupo", nullable = false, precision = 8, scale = 0)
	public int getIdgrupo() {
		return this.idgrupo;
	}

	public void setIdgrupo(int idgrupo) {
		this.idgrupo = idgrupo;
	}

	@Column(name = "nivel", nullable = false, precision = 8, scale = 0)
	public int getNivel() {
		return this.nivel;
	}

	public void setNivel(int nivel) {
		this.nivel = nivel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profesores")
	public Set<Grupo> getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Set<Grupo> grupos) {
		this.grupos = grupos;
	}

}
